fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v7.1.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '5.2.0'
    sshkeys:
      repo: 'https://github.com/puppetlabs/puppetlabs-sshkeys_core.git'
      ref: '1.0.2'
      puppet_version: '>= 6.0.0'
