fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '2.2.1'
    common:
      repo: 'https://github.com/ghoneycutt/puppet-module-common.git'
      ref: 'v1.4.1'
    firewall:
      repo: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: '3.2.0'
    sshkeys:
      repo: 'git://github.com/puppetlabs/puppetlabs-sshkeys_core.git'
      ref: '1.0.1'
  symlinks:
    ssh: "#{source_dir}"
