---
inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

inherit_gem:
  voxpupuli-rubocop: rubocop.yml

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - Vagrantfile
    - spec/fixtures/**/*
