# This file can be used to customize the files managed by PDK.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el8
      - el9
      - debian-11
      - ubuntu-2004
      - ubuntu-2204
    puppet:
      - puppet7
      - puppet8
.github/workflows/release.yaml:
  username: ghoneycutt
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
  hiera_config: spec/hiera.yaml
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
