name    'ghoneycutt-ssh'
version '2.0.0'
source 'git://github.com/ghoneycutt/puppet-module-ssh.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manages SSH'
description 'Manage SSH'
project_page 'https://github.com/ghoneycutt/puppet-module-ssh'

dependency 'puppetlabs/stdlib',  '3.2.x'
dependency 'ghoneycutt/common',  '0.0.1'
dependency 'puppetlabs/firewall', '>= 0.2.1'
