name    'ghoneycutt-ssh'
version '3.17.0'
source 'git://github.com/ghoneycutt/puppet-module-ssh.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manages SSH'
description 'Manage SSH'
project_page 'https://github.com/ghoneycutt/puppet-module-ssh'

dependency 'puppetlabs/stdlib',   '>= 3.2.0'
dependency 'ghoneycutt/common',   '>= 1.0.2'
dependency 'puppetlabs/firewall', '>= 0.2.1'
